
FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -B clean package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/recommendation-feature-1.0.jar app.jar

EXPOSE 10000

CMD ["java", "-jar", "app.jar"]